AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-bia

  Sample SAM Template for sam-bia
  

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'http://localhost:3001'"

Resources:

  TarefasFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bia/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /api/ping
            Method: get        
        GetTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: post
        GetTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriority:
          Type: Api
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete    
        Getversao:
          Type: Api
          Properties:
            Path: /api/versao
            Method: get
      Environment:
        Variables:
          DB_HOST: bia.cgbk82so41lk.us-east-1.rds.amazonaws.com
          DB_PORT: 5432
          DB_USER: postgres
          DB_PWD: URBCLSRtTesrs5lrB3Tr
      VpcConfig: 
        SecurityGroupIds:
          - sg-04454b466db48c6c3
        SubnetIds:
          - subnet-0b1c98caf28dafe11
          - subnet-0add0efa710bcbf7e
Outputs:
  TarefasApi:
    Description: "API Gateway endpoint URL for Prod stage for Tarefas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/api/tarefas"
  TarefasFunction:
    Description: "Tarefas Lambda Function ARN"
    Value: !GetAtt TarefasFunction.Arn
  TarefasFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TarefasFunctionRole.Arn
