AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-bia

  Sample SAM Template for sam-bia
  

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'http://localhost:3001'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  TarefasFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bia/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: post
        GetTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriority:
          Type: Api
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefa:
          Type: Api
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete    
        Getversao:
          Type: Api
          Properties:
            Path: /api/versao
            Method: get
      Environment:
        Variables:
          DB_HOST: "database"
          DB_PORT: 5432
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
